apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: backend
  labels:
    name: backend
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: backend
    weight: 100
  wildcardPolicy: None
